baseURL = "https://giordano-menegazzi.github.io/"
languageCode = "en-us"
theme = "raditian"
canonifyURLs = "true"


# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "iOS Apps"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4


# params
[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "contact"]
  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "iOS Portfolio"
    text2 = "G. Menegazzi"

  [params.footer]
      copyright = "© Hanni's Engineering. All rights reserved."
      [params.footer.radity_logo]
        x = "img/footer/Logo-Outlines-White.png"
        _2x = "img/footer/Logo-Outlines-White@2x.png"
